binary_sensor:
  # Bureau
  - platform: homeassistant
    id: bureau_light_state
    entity_id: light.ampoule_bureau
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda 'return x;'

  # Fado bureau
  - platform: homeassistant
    id: fado_bureau_light_state
    entity_id: light.0x001788010dc8ba13
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_scene_calls_button
          state:
            checked: !lambda 'return x;'

  # Chambre
  - platform: homeassistant
    id: chambre_light_state
    entity_id: light.0x001788010c014263
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda 'return x;'

  # Led chambre
  - platform: homeassistant
    id: led_chambre_light_state
    entity_id: light.0x001788010c58b8f2
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_scene_dimmed_button
          state:
            checked: !lambda 'return x;'

  # Salon
  - platform: homeassistant
    id: salon_light_state
    entity_id: light.0x00178801062d1c11
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_blind_open_button
          state:
            checked: !lambda 'return x;'

  # Salle à manger
  - platform: homeassistant
    id: salle_a_manger_light_state
    entity_id: light.0x001788010dc8c061
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_blind_66_button
          state:
            checked: !lambda 'return x;'

  # La boule
  - platform: homeassistant
    id: la_boule_light_state
    entity_id: light.la_boule
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_blind_33_button
          state:
            checked: !lambda 'return x;'

  # Salle de bain
  - platform: homeassistant
    id: salle_de_bain_light_state
    entity_id: light.0x001788010c0adbc8
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_blind_close_button
          state:
            checked: !lambda 'return x;'

  # Cuisine
  - platform: homeassistant
    id: cuisine_light_state
    entity_id: light.0x001788010c2dee03
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: printer_power_button
          state:
            checked: !lambda 'return x;'

  # Led cuisine
  - platform: homeassistant
    id: led_cuisine_light_state
    entity_id: light.0x001788010d0b3aa9
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: filament_heater_button
          state:
            checked: !lambda 'return x;'

  # Couloir
  - platform: homeassistant
    id: couloir_light_state
    entity_id: light.0x001788010c2de07e
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: office_aircon_button
          state:
            checked: !lambda 'return x;'

  # Lampe couloir (prise)
  - platform: homeassistant
    id: lampe_couloir_switch_state
    entity_id: switch.lampe_couloir
    trigger_on_initial_state: true
    on_state:
      - lvgl.widget.update:
          id: battery_charger_button
          state:
            checked: !lambda 'return x;'


sensor:
  # Température intérieure
  - platform: homeassistant
    id: indoor_temperature
    entity_id: sensor.office_temperature
    internal: true
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%.0f° / -°"
            args:
              - x

  # Température extérieure
  - platform: homeassistant
    id: outdoor_temperature
    entity_id: sensor.outdoor_temperature
    internal: true
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%.0f° / %.0f°"
            args:
              - id(indoor_temperature).state
              - x

  # Bureau - luminosité réelle
  - platform: homeassistant
    id: bureau_brightness
    entity_id: light.ampoule_bureau
    attribute: brightness
    internal: true
    filters:
      - multiply: 0.3921568627
    on_value:
      - lvgl.label.update:
          id: selected_light_brightness
          text:
            format: "Lum : %.0f%%"
            args:
              - x


text_sensor:
  # Heure
  - platform: homeassistant
    id: current_time_ha
    entity_id: sensor.time
    internal: true
    on_value:
      - lvgl.label.update:
          id: display_time
          text:
            format: "%s"
            args:
              - x.c_str()


